name: psot new code on linkedIn
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GETTING FOLDER NAME
    runs-on: ubuntu-latest
    if: ${{contains(github.event.head_commit.message, 'Create README - LeetHub')}}  
    steps:
    - name: taking last commit
      uses: Stockopedia/action-get-changed-files@v1
      id: get_changed_folders
      with:
        github-token: ${{ secrets.TOKEN || github.token }}
        ignore: "**/+(.github)"
        foldersOnly: true 
        format: csv
    - name: Checkout
      uses: actions/checkout@v2
    - name: Publish PDF Document
      uses: shrink/actions-document-publish@v1
      id: publish-document
      with:
      
        sources: "${{steps.get_changed_folders.outputs.changed}}/README.md"
    - name: Upload Document
      uses: actions/upload-artifact@v2
      id: upload-document
      with:
        name: '${{steps.get_changed_folders.outputs.changed}}.pdf'
        path: ${{ steps.publish-document.outputs.pdf }}


      # - uses: actions/checkout@v2
      # - name: post new code on linkedIn
      #   uses: linkedin/jobs-api-posting-action@master
      #   with:
      #     linkedin-oauth2-access-token: ${{ secrets.LINKEDIN_OAUTH2_ACCESS_TOKEN }}
      #     linkedin-oauth2-refresh-token: ${{ secrets.LINKEDIN_OAUTH2_REFRESH_TOKEN }}
      #     linkedin-oauth2-client-id: ${{ secrets.LINKEDIN_OAUTH2_CLIENT_ID }}
      #     linkedin-oauth2-client-secret: ${{ secrets.LINKEDIN_OAUTH2_CLIENT_SECRET }}
      #     linkedin-company-id: ${{ secrets.LINKEDIN_COMPANY_ID }}
      #     linkedin-job-posting-json: ${{ secrets.LINKEDIN_JOB_POSTING_JSON }}
